// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/SwissGridCRMDashboard-QqzHIN/App.tsx": () => import("../components/mockups/templates/SwissGridCRMDashboard-QqzHIN/App.tsx"),
  "./components/mockups/templates/SwissGridCRMDashboard-eYGCQd/App.tsx": () => import("../components/mockups/templates/SwissGridCRMDashboard-eYGCQd/App.tsx")
};
